-- noinspection SqlNoDataSourceInspectionForFile
DROP TABLE IF EXISTS `RECIPE`;

CREATE TABLE RECIPE
(
    ID          INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME        VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    INGREDIENTS VARCHAR(255) NOT NULL,
    DIRECTIONS  VARCHAR(255) NOT NULL,
    SERVINGS    INT          NOT NULL,
    PREP_TIME   INT          NOT NULL
);