name: Code check
on: [ push ]
jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    env:
      GIN_MODE: release
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      # Setup Maven
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3

      # Run unit-test
      - name: Run unit-test
        run: |
          mvn test

  lint-check:
    name: lint-check
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      # Setup Maven
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3

      # Run lint-check
      - name: Run lint-check using google code style
        run: |
          mvn checkstyle:check -Dcheckstyle.config.location=google_checks.xml -Dcheckstyle.consoleOutput=true

  code-coverage:
    name: Generate code coverage report
    runs-on: ubuntu-latest
    steps:
      - name: jacoco-badge-generator
        uses: cicirello/jacoco-badge-generator@v2.8.1

