name: Code check
on: [ push ]
jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    env:
      GIN_MODE: release
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      # Setup Maven
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3

      # Run unit-test
      - name: Run unit-test
        run: |
          mvn test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true

  lint-check:
    name: lint-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          skip-commit: true
      - name: Print diffs
        run: git --no-pager diff --exit-code

